// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD93W4BGgwbWNP7lnIsVJbZwxSNX0Kmmnk',
    appId: '1:616658152835:web:9d19a43bce2d12070a1ab6',
    messagingSenderId: '616658152835',
    projectId: 'blog-app-32e25',
    authDomain: 'blog-app-32e25.firebaseapp.com',
    storageBucket: 'blog-app-32e25.firebasestorage.app',
    measurementId: 'G-70RTRNGT7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdoopws6_sn4p6ICpc71D1RHxyqxOJR54',
    appId: '1:616658152835:android:a595fcc85974ead30a1ab6',
    messagingSenderId: '616658152835',
    projectId: 'blog-app-32e25',
    storageBucket: 'blog-app-32e25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq0kMpeCYwORBgyynOMP86rG65UMDIBv0',
    appId: '1:616658152835:ios:995cbd93514294740a1ab6',
    messagingSenderId: '616658152835',
    projectId: 'blog-app-32e25',
    storageBucket: 'blog-app-32e25.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq0kMpeCYwORBgyynOMP86rG65UMDIBv0',
    appId: '1:616658152835:ios:995cbd93514294740a1ab6',
    messagingSenderId: '616658152835',
    projectId: 'blog-app-32e25',
    storageBucket: 'blog-app-32e25.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );
}
